[#ftl]
[#--https://www.jetbrains.com/help/idea/template-languages-velocity-and-freemarker.html--]

[#-- @implicitly included --]
[#-- @ftlvariable name="content" type="info.magnolia.jcr.util.ContentMap" --]
[#-- @ftlvariable name="ctx" type="info.magnolia.context.MgnlContext" --]
[#-- @ftlvariable name="def" type="info.magnolia.rendering.template.configured.ConfiguredTemplateDefinition" --]
[#-- @ftlvariable name="state" type="info.magnolia.cms.core.AggregationState" --]
[#-- @ftlvariable name="i18n" type="info.magnolia.freemarker.MessagesWrapper" --]
[#-- @ftlvariable name="i18nAuthoring" type="info.magnolia.freemarker.MessagesWrapper" --]

[#-- @ftlvariable name="cms" type="info.magnolia.templating.freemarker.Directives" --]
[#-- @ftlvariable name="cmsfn" type="info.magnolia.templating.functions.TemplatingFunctions" --]
[#-- @ftlvariable name="sitefn" type="info.magnolia.module.site.functions.SiteFunctions" --]
[#-- @ftlvariable name="imgfn" type="info.magnolia.imaging.functions.ImagingTemplatingFunctions" --]
[#-- @ftlvariable name="damfn" type="info.magnolia.dam.templating.functions.DamTemplatingFunctions" --]
[#-- @ftlvariable name="searchfn" type="info.magnolia.templating.functions.SearchTemplatingFunctions" --]
[#-- @ftlvariable name="catfn" type="info.magnolia.module.categorization.functions.CategorizationTemplatingFunctions" --]
[#-- @ftlvariable name="restfn" type="info.magnolia.resteasy.client.functions.RestTemplatingFunctions" --]
[#-- @ftlvariable name="navfn" type="info.magnolia.templating.functions.NavigationTemplatingFunctions" --]

[#-- @ftlvariable name="contextPath" type="java.lang.String" --]
[#-- @ftlvariable name="actionResult" type="java.lang.String" --]
[#-- @ftlvariable name="defaultBaseUrl" type="java.lang.String" --]
