[#assign index = 0]
[#list components as component]
    [@cms.component content=component contextAttributes={"maxIndex": components?size - 1, "orderIndex": index, "cell": ctx.cell!, "parentOrderIndex": ctx.orderIndex!} /]
    [#assign index = index + 1 /]
[/#list]
